#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "TheFinalTake/Career/FTCareerTypes.h"
#include "FTEconomy.generated.h"

class UFTCareerSave;

/**
 * Every balance number of the career loop: audience formula, ticket split, tiers, starting money
 * and the catalogues (shop items, cars, studio expansions). The class constructor authors the
 * defaults; the data asset /Game/TheFinalTake/Data/DA_Economy (generated by the content
 * commandlet) is what designers edit. See CAREER_ECONOMY.md for the formulas.
 */
UCLASS(BlueprintType)
class THE_FINAL_TAKE_API UFTEconomyConfig : public UPrimaryDataAsset
{
	GENERATED_BODY()

public:
	UFTEconomyConfig();

	// ---------------------------------------------------------------- audience formula
	/** Walk-in crowd every release gets, even a bad one. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Audience") int32 BaseAudience = 800;
	/** Extra audience for a perfect (100) film. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Audience") int32 QualityAudience = 9000;
	/** >1: good films pull clearly ahead, mediocre ones stay affordable. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Audience") float QualityExponent = 1.6f;
	/** +audience per production point of visibly used upgrades. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Audience") float ProductionPctPerPoint = 0.01f;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Audience") int32 MaxProductionPoints = 35;
	/** Premiere punctuality bonus (share of the night left when the premiere starts). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Audience") float ArrivalBonusMaxPct = 0.15f;
	/** Remaining-night fraction that already earns the full punctuality bonus. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Audience") float ArrivalFullBonusAt = 0.5f;
	/** Studio condition below which the damage penalty starts. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Audience") float ConditionPenaltyBelow = 60.f;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Audience") float ConditionPenaltyPerPoint = 0.005f;
	/** "Behind the scenes" buzz when the crew finished the film through its disaster. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Audience") float DisasterBuzzPct = 0.04f;
	/** Re-releasing the same film loses this share per earlier release... */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Audience") float SequelFatiguePerRelease = 0.1f;
	/** ...but never drops below this factor. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Audience") float MinSequelFactor = 0.6f;
	/** Seeded, purely cosmetic word-of-mouth swing (+/-). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Audience") float WordOfMouthPct = 0.02f;

	// ---------------------------------------------------------------- money
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Money") int32 TicketPrice = 10;
	/** Part of the ticket money that reaches the studio. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Money") float StudioShare = 0.5f;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Money") int32 StartingMoney = 5000;

	// ---------------------------------------------------------------- tiers
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Tiers") int32 ModestAudience = 3000;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Tiers") int32 SolidAudience = 5500;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Tiers") int32 HitAudience = 8000;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Tiers") int32 BlockbusterAudience = 11000;
	/** Weak film with lots of visible production value = cult classic. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Tiers") int32 CultMaxQuality = 60;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Tiers") int32 CultMinProduction = 12;

	// ---------------------------------------------------------------- premiere
	/** Seats in the city cinema (audience crowd fills them proportionally). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Premiere") int32 CinemaSeats = 240;
	/** Audience that fills the cinema completely. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Premiere") int32 FullHouseAudience = 12000;

	// ---------------------------------------------------------------- catalogues
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Catalogue") TArray<FFTShopItemDef> Items;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Catalogue") TArray<FFTVehicleDef> Vehicles;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Catalogue") TArray<FFTStageDef> Stages;

	virtual FPrimaryAssetId GetPrimaryAssetId() const override { return FPrimaryAssetId(TEXT("FTEconomy"), TEXT("Default")); }

	/** Data asset first, then the authored defaults. Never null. */
	static const UFTEconomyConfig* Get();

	const FFTShopItemDef* FindItem(FName ItemId) const;
	const FFTVehicleDef* FindVehicle(FName VehicleId) const;
	const FFTStageDef* FindStage(FName StageId) const;
	const FFTStageDef* FindStageForFilm(FName FilmId) const;
	/** Price and category of any purchasable id (item, vehicle or stage). False if unknown. */
	bool Describe(FName Id, int32& OutPrice, EFTShopCategory& OutCategory, FText& OutName) const;
};

/** Pure release / box-office maths. No world access: everything comes in through FFTReleaseInput. */
struct THE_FINAL_TAKE_API FFTEconomy
{
	static FFTReleaseReport ComputeRelease(const FFTReleaseInput& In, const UFTEconomyConfig& Cfg);
	/** Rank the report among the studio's earlier releases (1 = most revenue). */
	static void RankRelease(FFTReleaseReport& Report, const TArray<FFTReleasedFilm>& Previous);
	static int32 StarsForQuality(int32 Quality);
	static EFTBoxOfficeTier TierFor(int32 Audience, int32 Quality, int32 ProductionPoints, const UFTEconomyConfig& Cfg);
	static FText TierName(EFTBoxOfficeTier Tier);
	static FText CategoryName(EFTShopCategory Category);
	/** Share of the cinema that is filled for an audience (0..1). */
	static float FillRatio(int32 Audience, const UFTEconomyConfig& Cfg);
	static FString MoneyString(int64 Amount);
	static FString NumberString(int64 Amount);
};

/** Result of a purchase attempt; the reason text is shown to the buyer. */
enum class EFTPurchaseResult : uint8
{
	Ok,
	UnknownItem,
	AlreadyOwned,
	NotEnoughMoney,
	NotAllowed
};

/**
 * Money/ownership rules on a career save. Server code (career manager) and the automation
 * tests both go through here, so the rules exist exactly once.
 */
struct THE_FINAL_TAKE_API FFTCareerLedger
{
	static bool Owns(const UFTCareerSave& Save, FName Id);
	static EFTPurchaseResult CanPurchase(const UFTCareerSave& Save, const UFTEconomyConfig& Cfg, FName Id, int32& OutPrice, EFTShopCategory& OutCategory);
	/** Deducts and grants atomically. Never leaves a negative balance. */
	static EFTPurchaseResult Purchase(UFTCareerSave& Save, const UFTEconomyConfig& Cfg, FName Id, int32& OutPrice);
	/** Credits a release; returns false (and changes nothing) if this release number was already booked. */
	static bool BookRelease(UFTCareerSave& Save, const FFTReleaseReport& Report);
	static FText ReasonText(EFTPurchaseResult Result, int32 Price, int32 Balance);
};
