#pragma once

#include "CoreMinimal.h"
#include "FTTypes.generated.h"

/** Low-poly mesh set generated by the content commandlet (falls back to engine basic shapes). */
UENUM(BlueprintType)
enum class EFTShape : uint8
{
	Cube,		// sharp 1m cube (architecture)
	Box,		// chamfered toy box
	Sphere,		// faceted icosphere (80 faces)
	Ball,		// rounder faceted icosphere (320 faces)
	Cylinder,	// 10-sided
	Cone,		// 10-sided
	Prism,		// isosceles triangular prism (fins, roofs)
	Ramp,		// right-angle wedge
	Torus,		// rings, reels, life buoy
	Capsule,	// limbs, bodies
	Plane,		// flat 1m quad
	WaterGrid,	// subdivided plane for waves
	Shoreline,	// continuous sculpted sand apron (visual only)
	CrewTorso	// tailored rounded jacket silhouette (visual only)
};

UENUM(BlueprintType)
enum class EFTInteractType : uint8
{
	Press,		// single press
	Hold,		// hold to confirm
	Continuous,	// held for as long as the key is down (e.g. pushing the boat)
	Carry		// pick up
};

UENUM(BlueprintType)
enum class EFTCostume : uint8
{
	None,
	Lifeguard,
	Shark,
	Raincoat,
	FoamKnight
};

UENUM(BlueprintType)
enum class EFTEmote : uint8
{
	None,
	Wave,
	Point,
	Cheer,
	Panic,
	HeroPose
};

UENUM(BlueprintType)
enum class EFTExpression : uint8
{
	Neutral,
	Happy,
	Panic,
	Confident,
	Confused,
	Exhausted
};

UENUM(BlueprintType)
enum class EFTShootPhase : uint8
{
	Title,		// standalone title screen
	Lobby,		// free roam before a script is chosen
	Shooting,	// scenes in progress
	Finale,		// projection room open, loading reels
	Premiere,	// montage playing
	Results,	// score card
	Failed		// blackout
};

UENUM(BlueprintType)
enum class EFTSceneState : uint8
{
	Preparation,
	ReadyToRoll,
	Recording,
	TakeComplete,
	Transition
};

UENUM(BlueprintType)
enum class EFTObjectiveState : uint8
{
	NotStarted,
	Available,
	InProgress,
	Complete,
	FailedOptional
};

UENUM(BlueprintType)
enum class EFTObjectiveType : uint8
{
	CostumeInZone,		// Param1 = costume name (Lifeguard/Shark/...), Param2 = zone tag
	DeviceActive,		// Param1 = device tag
	PropInZone,			// Param1 = prop tag, Param2 = zone tag
	HeldPropInZone,		// Param1 = prop tag, Param2 = zone tag (someone carries it there)
	CameraOperated,
	SharkRigRaised,
	PowerRestored,
	KeyAction,			// Param1 = gameplay event that must happen while recording
	HoldShot,			// keep the frame valid for the scene capture duration
	EventDuringRecording // optional bonus event while recording (Param1 = event)
};

UENUM(BlueprintType)
enum class EFTTakeRating : uint8
{
	Retake,
	Usable,
	Great,
	Perfect
};

UENUM(BlueprintType)
enum class EFTFloodStage : uint8
{
	Dry,
	Leaking,
	Flooded
};

UENUM(BlueprintType)
enum class EFTSceneDisaster : uint8
{
	None,
	FloodAfterTake,
	ProjectionUnlockAfterTake
};

UENUM(BlueprintType)
enum class EFTAnnounceStyle : uint8
{
	Info,
	Slate,		// big clapperboard banner
	Success,
	Danger,
	Hint
};

USTRUCT(BlueprintType)
struct FFTObjectiveDefinition
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadOnly) FName ObjectiveId;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) FText Text;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) bool bCritical = true;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) EFTObjectiveType Type = EFTObjectiveType::DeviceActive;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) FName Param1;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) FName Param2;
	/** Short call-out shown when the objective becomes available, e.g. "Someone start the rain!" */
	UPROPERTY(EditAnywhere, BlueprintReadOnly) FText Callout;
};

USTRUCT(BlueprintType)
struct FFTSceneDefinition
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadOnly) FName SceneId;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) FText Title;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, meta = (MultiLine = true)) FText ScriptDescription;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) FText SlateText;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) TArray<FFTObjectiveDefinition> Objectives;
	/** Subject tags that must be framed (scene-tagged actors/props/characters). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly) TArray<FName> RequiredSubjects;
	/** Props that give set-dressing points when in frame. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly) TArray<FName> BonusProps;
	/** Gameplay events counted as useful light/sound cues while recording. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly) TArray<FName> CueEvents;
	/** Devices whose active state counts as a useful cue while recording. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly) TArray<FName> CueDevices;
	/** Event that counts as the scene's key action. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly) FName KeyActionEvent;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) float CaptureDuration = 3.f;
	/** Maximum recording length before the take is cut automatically. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly) float CompletionWindow = 30.f;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) EFTSceneDisaster DisasterAfterTake = EFTSceneDisaster::None;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) FText TransitionText;
	UPROPERTY(EditAnywhere, BlueprintReadOnly) FText ScoreHint;
};

USTRUCT(BlueprintType)
struct FFTObjectiveStatus
{
	GENERATED_BODY()

	UPROPERTY(BlueprintReadOnly) FName ObjectiveId;
	UPROPERTY(BlueprintReadOnly) EFTObjectiveState State = EFTObjectiveState::NotStarted;
	UPROPERTY(BlueprintReadOnly) float Progress = 0.f;
};

USTRUCT(BlueprintType)
struct FFTTakeResult
{
	GENERATED_BODY()

	UPROPERTY(BlueprintReadOnly) FName FilmId;
	UPROPERTY(BlueprintReadOnly) FName SceneId;
	UPROPERTY(BlueprintReadOnly) int32 SceneIndex = 0;
	UPROPERTY(BlueprintReadOnly) int32 TakeNumber = 1;
	UPROPERTY(BlueprintReadOnly) int32 Score = 0;
	UPROPERTY(BlueprintReadOnly) EFTTakeRating Rating = EFTTakeRating::Retake;
	UPROPERTY(BlueprintReadOnly) int32 ActionPoints = 0;
	UPROPERTY(BlueprintReadOnly) int32 SubjectPoints = 0;
	UPROPERTY(BlueprintReadOnly) int32 CuePoints = 0;
	UPROPERTY(BlueprintReadOnly) int32 PropPoints = 0;
	UPROPERTY(BlueprintReadOnly) int32 StylePoints = 0;
	UPROPERTY(BlueprintReadOnly) TArray<FString> Reasons;
	UPROPERTY(BlueprintReadOnly) TArray<FName> VisibleSubjects;
	UPROPERTY(BlueprintReadOnly) TArray<FName> ActiveEffects;
	UPROPERTY(BlueprintReadOnly) int32 DisasterFlags = 0;
	UPROPERTY(BlueprintReadOnly) float Timestamp = 0.f;
	UPROPERTY(BlueprintReadOnly) bool bAccepted = false;
};

/** Live composition feedback for the camera operator. */
USTRUCT(BlueprintType)
struct FFTFrameReport
{
	GENERATED_BODY()

	UPROPERTY(BlueprintReadOnly) float Quality = 0.f;
	UPROPERTY(BlueprintReadOnly) TArray<FName> Subjects;
	UPROPERTY(BlueprintReadOnly) TArray<float> SubjectScores;
	UPROPERTY(BlueprintReadOnly) bool bCriticalValid = false;
	UPROPERTY(BlueprintReadOnly) float SmokeObstruction = 0.f;
};

namespace FTTags
{
	// Zones
	static const FName ZoneBeach(TEXT("Zone.Beach"));
	static const FName ZoneTank(TEXT("Zone.Tank"));
	static const FName ZoneHeroMark(TEXT("Zone.HeroMark"));
	static const FName ZoneLungeMark(TEXT("Zone.LungeMark"));
	static const FName ZoneSafe(TEXT("Zone.Safe"));
	static const FName ZoneRecovery(TEXT("Zone.Recovery"));
	static const FName ZoneOffice(TEXT("Zone.Office"));
	// Devices
	static const FName DevLighthouse(TEXT("Device.Lighthouse"));
	static const FName DevWind(TEXT("Device.Wind"));
	static const FName DevRain(TEXT("Device.Rain"));
	static const FName DevSmoke(TEXT("Device.Smoke"));
	static const FName DevFoam(TEXT("Device.Foam"));
	static const FName DevKeyLight(TEXT("Device.Light.1"));
	static const FName DevFillLight(TEXT("Device.Light.2"));
	static const FName DevHeroLight(TEXT("Device.Light.3"));
	// Subjects
	static const FName SubjLifeguard(TEXT("Subject.Lifeguard"));
	static const FName SubjLighthouse(TEXT("Subject.Lighthouse"));
	static const FName SubjFin(TEXT("Subject.Fin"));
	static const FName SubjBoat(TEXT("Subject.Boat"));
	static const FName SubjShark(TEXT("Subject.Shark"));
	static const FName SubjStorm(TEXT("Subject.Storm"));
	static const FName SubjHero(TEXT("Subject.Hero"));
	static const FName SubjHarpoon(TEXT("Subject.Harpoon"));
	static const FName SubjLifeRing(TEXT("Subject.LifeRing"));
	static const FName SubjCrate(TEXT("Subject.Crate"));
	static const FName SubjLamp(TEXT("Subject.Lamp"));
	static const FName SubjFinMarker(TEXT("Subject.FinMarker"));
	// Props
	static const FName PropBoat(TEXT("Prop.Boat"));
	static const FName PropHarpoon(TEXT("Prop.Harpoon"));
	static const FName PropReel(TEXT("Prop.Reel"));
	// Events
	static const FName EvSiren(TEXT("Cue.Siren"));
	static const FName EvStorm(TEXT("Cue.Storm"));
	static const FName EvSting(TEXT("Cue.Sting"));
	static const FName EvFinGlide(TEXT("Action.FinGlide"));
	static const FName EvSharkAttackBoat(TEXT("Action.SharkAttackBoat"));
	static const FName EvSharkDefeat(TEXT("Action.SharkDefeat"));
	static const FName EvRigLunge(TEXT("Shark.RigLunge"));
	static const FName EvCostumeLunge(TEXT("Shark.CostumeLunge"));
	static const FName EvFoam(TEXT("Mishap.Foam"));
	static const FName EvKnockdown(TEXT("Mishap.Knockdown"));
	static const FName EvEmotePoint(TEXT("Emote.Point"));
	static const FName EvEmoteCheer(TEXT("Emote.Cheer"));
	static const FName EvEmotePanic(TEXT("Emote.Panic"));
	static const FName EvHeroThrust(TEXT("Action.HeroThrust"));
	// Films
	static const FName FilmJaws(TEXT("JawsOfTheStudio"));
	static const FName FilmMoonfall(TEXT("MoonfallMotel"));
	static const FName FilmCastle(TEXT("CastleOnFire"));
}
